"""add user_writing_styles table

Revision ID: 099d0abc4115
Revises: 7f0f67a2f4d1
Create Date: 2026-05-03 21:18:37.653648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '099d0abc4115'
down_revision: Union[str, Sequence[str], None] = '7f0f67a2f4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_writing_styles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_writing_styles_user_id')
    )
    op.create_index('ix_user_writing_styles_user_id_updated_at', 'user_writing_styles', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_writing_styles_user_id_updated_at', table_name='user_writing_styles')
    op.drop_table('user_writing_styles')
    # ### end Alembic commands ###
