"""baseline_schema

Revision ID: 4ab839bda132
Revises: 
Create Date: 2026-03-30 21:56:25.562213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab839bda132'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('storage_quota', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('backup_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_backup_records_user_entity')
    )
    op.create_index('ix_backup_records_user_id_entity_type', 'backup_records', ['user_id', 'entity_type'], unique=False)
    op.create_index('ix_backup_records_user_id_updated_at', 'backup_records', ['user_id', 'updated_at'], unique=False)
    op.create_table('fragment_folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_fragment_folders_user_name')
    )
    op.create_table('knowledge_docs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('vector_ref_id', sa.String(), nullable=True),
    sa.Column('style_description', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('source_mime_type', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('media_kind', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_assets_user_id_created_at', 'media_assets', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_media_assets_user_id_media_kind', 'media_assets', ['user_id', 'media_kind'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_payload_json', sa.Text(), nullable=True),
    sa.Column('output_payload_json', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_pipeline_type_created_at', 'pipeline_runs', ['pipeline_type', 'created_at'], unique=False)
    op.create_index('ix_pipeline_runs_status_next_retry_at', 'pipeline_runs', ['status', 'next_retry_at'], unique=False)
    op.create_index('ix_pipeline_runs_user_id_created_at', 'pipeline_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('source_fragment_ids', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_daily_push', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_media_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('media_asset_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id', 'content_type', 'content_id', 'role', name='uq_content_media_links_asset_content_role')
    )
    op.create_index('ix_content_media_links_content_type_content_id', 'content_media_links', ['content_type', 'content_id'], unique=False)
    op.create_table('fragments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('audio_storage_provider', sa.String(), nullable=True),
    sa.Column('audio_bucket', sa.String(), nullable=True),
    sa.Column('audio_object_key', sa.String(), nullable=True),
    sa.Column('audio_access_level', sa.String(), nullable=True),
    sa.Column('audio_original_filename', sa.String(), nullable=True),
    sa.Column('audio_mime_type', sa.String(), nullable=True),
    sa.Column('audio_file_size', sa.Integer(), nullable=True),
    sa.Column('audio_checksum', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('speaker_segments', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('plain_text_snapshot', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('audio_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['fragment_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fragments_user_id_folder_id', 'fragments', ['user_id', 'folder_id'], unique=False)
    op.create_table('pipeline_step_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('input_payload_json', sa.Text(), nullable=True),
    sa.Column('output_payload_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_ref_json', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_token', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'step_name', name='uq_pipeline_step_runs_run_step')
    )
    op.create_index('ix_pipeline_step_runs_pipeline_run_id_step_order', 'pipeline_step_runs', ['pipeline_run_id', 'step_order'], unique=False)
    op.create_index('ix_pipeline_step_runs_status_available_at', 'pipeline_step_runs', ['status', 'available_at'], unique=False)
    op.create_table('fragment_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('fragment_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragment_id', 'tag', name='uq_fragment_tags_user_fragment_tag')
    )
    op.create_index('ix_fragment_tags_user_id_tag', 'fragment_tags', ['user_id', 'tag'], unique=False)
    op.create_foreign_key(None, 'backup_restore_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'device_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'fragment_blocks', 'fragments', ['fragment_id'], ['id'])
    op.create_foreign_key(None, 'methodology_entries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'stable_core_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stable_core_profiles', type_='foreignkey')
    op.drop_constraint(None, 'methodology_entries', type_='foreignkey')
    op.drop_constraint(None, 'fragment_blocks', type_='foreignkey')
    op.drop_constraint(None, 'device_sessions', type_='foreignkey')
    op.drop_constraint(None, 'backup_restore_sessions', type_='foreignkey')
    op.drop_index('ix_fragment_tags_user_id_tag', table_name='fragment_tags')
    op.drop_table('fragment_tags')
    op.drop_index('ix_pipeline_step_runs_status_available_at', table_name='pipeline_step_runs')
    op.drop_index('ix_pipeline_step_runs_pipeline_run_id_step_order', table_name='pipeline_step_runs')
    op.drop_table('pipeline_step_runs')
    op.drop_index('ix_fragments_user_id_folder_id', table_name='fragments')
    op.drop_table('fragments')
    op.drop_index('ix_content_media_links_content_type_content_id', table_name='content_media_links')
    op.drop_table('content_media_links')
    op.drop_table('scripts')
    op.drop_index('ix_pipeline_runs_user_id_created_at', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_status_next_retry_at', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_pipeline_type_created_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_media_assets_user_id_media_kind', table_name='media_assets')
    op.drop_index('ix_media_assets_user_id_created_at', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('knowledge_docs')
    op.drop_table('fragment_folders')
    op.drop_index('ix_backup_records_user_id_updated_at', table_name='backup_records')
    op.drop_index('ix_backup_records_user_id_entity_type', table_name='backup_records')
    op.drop_table('backup_records')
    op.drop_table('users')
    # ### end Alembic commands ###
