"""add_updated_at_to_fragments

Revision ID: c090100cca09
Revises: c1d2e3f4a5b6
Create Date: 2026-03-14 13:34:48.279801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c090100cca09'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加列为可空，填充数据后再设为非空
    op.add_column('fragments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # 为现有数据设置 updated_at = created_at
    op.execute("UPDATE fragments SET updated_at = created_at WHERE updated_at IS NULL")
    # 现在设为非空
    op.alter_column('fragments', 'updated_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    op.alter_column('fragments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_docs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # 添加索引以优化按 updated_at 排序的查询
    op.create_index('ix_fragments_updated_at', 'fragments', ['updated_at'])
    # 添加复合索引以优化按用户和时间排序的查询
    op.create_index('ix_fragments_user_updated', 'fragments', ['user_id', 'updated_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fragments_user_updated', table_name='fragments')
    op.drop_index('ix_fragments_updated_at', table_name='fragments')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('scripts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('knowledge_docs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('fragments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('fragments', 'updated_at')
    # ### end Alembic commands ###
