"""Audio processing constants."""

AUDIO_SAMPLE_RATE = 16000
CHUNK_SIZE_BYTES = 3200
BYTES_PER_SECOND = 32000
WAV_HEADER_SIZE = 44
MIN_RECOGNITION_WAIT_SECONDS = 10
RECOGNITION_TIMEOUT_BUFFER_SECONDS = 5
RECOGNITION_POLL_INTERVAL_SECONDS = 0.1
